name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Flutter version
      run: flutter --version

    - name: Install dependencies
      run: flutter pub get

    - name: Build iOS no codesign
      run: |
        flutter build ios --release --no-codesign

    - name: Create IPA
      run: |
        cd build/ios/iphoneos
        mkdir Payload
        cp -r Runner.app Payload/
        zip -qq -r unsigned.ipa Payload

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: iOS-IPA
        path: build/ios/iphoneos/unsigned.ipa
